apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  labels:
    app: weather-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app
        image: krishna112/weather-app:v6
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: weather-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: weather-app
  ports:
    - port: 80
      targetPort: 5000