apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  labels:
    app: weather-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app
        image: krishna112/weather-app:v7
        ports:
        - containerPort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: weather-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-west-1:314969690343:certificate/49bc07f8-586e-4f9c-beb0-721e79fd92b2
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
spec:
  type: LoadBalancer
  selector:
    app: weather-app
  ports:
    - name: http
      port: 80
      targetPort: 5000
    - name: https
      port: 443
      targetPort: 5000